# Generated by Django 4.2.17 on 2025-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='type',
            field=models.CharField(choices=[('Battery', 'Battery'), ('Other Item', 'Other Item')], default='Battery', max_length=20),
        ),
    ]
