# Generated by Django 4.2.17 on 2025-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_producttype_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Product Types', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'verbose_name': 'Warranty Claims', 'verbose_name_plural': 'Warranty Claims'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.TextField(blank=True),
        ),
    ]
