# Generated by Django 4.2.17 on 2024-12-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
