# Generated by Django 4.2.17 on 2025-01-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='productName',
            new_name='product',
        ),
    ]
